gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of {COLOR GREEN}Pokémon{COLOR DARK_GRAY}!\p"
	.string "My name is {COLOR GREEN}Cypress{COLOR DARK_GRAY}.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative teammates.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "I research {COLOR GREEN}Mythical Pokémon{COLOR DARK_GRAY} of\n"
	.string "centuries past.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Enough about me...\n"
	.string "What about you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a {COLOR BLUE}boy{COLOR DARK_GRAY}?\n"
	.string "Or are you a {COLOR RED}girl{COLOR DARK_GRAY}?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "Ah, so it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, yes!\p"
	.string "You're {PLAYER}{KUN} of {COLOR GREEN}Canvas Town{COLOR DARK_GRAY}.\n"
	.string "A small town in {COLOR GREEN}West Ryoko{COLOR DARK_GRAY}. Pleasant\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "I'll be visiting {COLOR GREEN}Canvas Town{COLOR DARK_GRAY},\n"
	.string "please come see me!\p"
	.string "$"
